###
POST http://nest.local/users/signup
Content-Type: application/json

{
  "email": "mmhp16@gmail.c2",
  "password": "zxczxc"
}

###
POST http://172.20.20.17:3000/users/signup
Content-Type: application/x-www-form-urlencoded

email=mmhp16@gmail.com&password=salamat

###
POST http://nest.local/users/getMe
Content-Type: application/json

{
  "email": "mmhp16@gmail.comvv",
  "password": "zxczxc"
}

###
POST {{host}}/users/test
Content-Type: application/json

{
  "email": "mmhp16@gmail.comvv",
  "password": "zxczxc"
}

###
POST {{host}}/users/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1taHAxNkB5YWhvby5jb20iLCJzdWIiOiI2NDBkOWIzZmE1ZGIxOGQ4NWFkMDk4NTYiLCJpYXQiOjE2Nzg2OTA3NTAsImV4cCI6MTY4MjkyNDM1MH0.Pju4YtWsgA_vnzvR-H1GoQyMCs9NmOKrV0I0al4xf-0

###

POST {{host}}/users/signIn
Content-Type: application/json

{
  "email": "mmhp16@gmail.comvv2",
  "password": "zxczxc"
}

###
POST {{host}}/users/jwtSignIn
Content-Type: application/json

{
  "email": "mmhp16@yahoo.com",
  "password": "3484634846"
}

###
POST {{host}}/users/signOut
Content-Type: application/json

{
  "email": "mmhp16@gmail.comvv2",
  "password": "zxczxc"
}

###