POST {{host}}/users/signup
Content-Type: application/json

{
  "email": "asdasd@gmail.com",
  "password": "test2",
  "firstName": "mehdi",
  "lastName": "hp"
}

###
POST {{host}}/users/signin
Content-Type: application/x-www-form-urlencoded

email=mmhp17@gmail.com&password=zxczxc

###
POST {{host}}/users/jwtSignIn
Content-Type: application/x-www-form-urlencoded

email=mmhp17@gmail.com&password=zxczxc

###
POST {{host}}/users/getMe
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1taHAxN0BnbWFpbC5jb20iLCJzdWIiOiI2M2Q3YjJjZWZlNjY1MjFiY2QwNzQwYTciLCJpYXQiOjE2ODA5NTMyMjEsImV4cCI6MTY4MzU0NTIyMX0.gCAots70OuFCFijpbUPrXXNw6K3rPx4DVfDzcrPySb0

###
POST {{host}}/users/signOut

###
POST {{host}}/users/signIn
Content-Type: application/json

{
  "email": "mmhp17@gmail.com",
  "password": "zxczxc"
}

###


POST {{host}}/users/setRoleId
Content-Type: application/json

{
  "roleId": "6405f315e6e08a8e6ddcdb42"
}

###
POST {{host}}/users/setProfile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1taHAxN0BnbWFpbC5jb20iLCJzdWIiOiI2M2Q3YjJjZWZlNjY1MjFiY2QwNzQwYTciLCJpYXQiOjE2ODA5NTMyMjEsImV4cCI6MTY4MzU0NTIyMX0.gCAots70OuFCFijpbUPrXXNw6K3rPx4DVfDzcrPySb0

{
  "email": "mmhp17@gmail.com",
  "password": "zxczxc",
  "firstName": "medhdo2",
  "lastName": "hpo"
}