POST {{host}}/users/signup
Content-Type: application/json

{
  "email": "asdasd@gmail.com",
  "password": "test2",
  "firstName": "mehdi",
  "lastName": "hp"
}

###
POST {{host}}/users/signin
Content-Type: application/x-www-form-urlencoded

email=mmhp17@gmail.com&password=zxczxc

###
POST {{host}}/users/jwtSignIn
Content-Type: application/x-www-form-urlencoded

email=mmhp17@gmail.com&password=zxczxc

###
POST {{host}}/users/getMe

###
POST {{host}}/users/signOut

###
POST {{host}}/users/signIn
Content-Type: application/json

{
  "email": "mmhp17@gmail.com",
  "password": "zxczxc"
}

###


POST {{host}}/users/setRoleId
Content-Type: application/json

{
  "roleId": "6405f315e6e08a8e6ddcdb42"
}

###