POST {{host}}/roles/store
Content-Type: application/json

{
  "title": "admin",
  "description": "this is main role for admin"
}

#####
POST {{host}}/roles/show
Content-Type: application/json

{
  "title": "bigHP2"
}

#####
POST {{host}}/roles/updatePermissions
Content-Type: application/json

{
  "roleId": "64356f1740243b368d15c499",
  "permissions": [
    "64072620f3e9f5214fe13db7",
    "6407262af3e9f5214fe13dba",
    "6407262ff3e9f5214fe13dbd",
    "64072634f3e9f5214fe13dc0",
    "64072639f3e9f5214fe13dc3",
    "64356b66426f6bff27fa4bb1"
  ]
}
